### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by GreenComfyTea** [cursey/reframework-d2d#1]
**Problem:**
If something goes wrong in `re.on_frame` it shows an error or just returns from the function. When using `d2d.register(init_fn, draw_fn)` if something goes wrong in `draw_fn` the game gets completely frozen and we have to restart the game.

**Desired behavior:**
Show an error or/and return from the function so the game could continue running.

**Comment by cursey** [comment]
I noticed this as well. I'll fix it.

**Comment by cursey** [comment]
Fixed in abfdda273fc0b1fe05a4093feec931324fd14721
