### ISSUE TITLE
Incorrect Premultiplied Alpha Blending

### ISSUE THREAD

**Issue by GreenComfyTea** [cursey/reframework-d2d#3]
**Problem:**
Alpha Blending (aka transparent colors) behave differently from imgui and photoshop. Lower opacity adds dirtiness (blackness) to the color.

**Possible reason:**
RGB channels are multiplied by alpha twice.

**Possible solution:**
1) Switch to Straight Alpha Blending
or
2) Manually divide RGB by alpha once(?).

**Screenshots:**
![alpha_test](https://user-images.githubusercontent.com/30152047/151696358-53575e8c-801b-4e4b-bc17-a82730b34250.png)

**Details:**
I looked it up [here](https://athenstean.com/blog/alpha-not-transparency-premultiplied-alpha-alpha-maps-trees-ios/) and [here](https://www.youtube.com/watch?v=-dK71TVrBLM).

![image](https://user-images.githubusercontent.com/30152047/151696383-fb7451d0-e45b-4d13-add0-8f50164cfd5f.png)

**Comment by cursey** [comment]
Provide the script you're using to test please.

**Comment by GreenComfyTea** [comment]
UPD.: It was the case when using old version of the plugin. It produces the correct alpha blending in v0.2.1. 
Sorry for the unnecessary issue.
![image](https://user-images.githubusercontent.com/30152047/151697021-de999bca-c8ef-45c1-8662-6773b838ce2d.png)
